/** Map of common .edu domains → university names for auto-fill. */
export const DOMAIN_TO_UNIVERSITY: Record<string, string> = {
  'harvard.edu': 'Harvard University',
  'yale.edu': 'Yale University',
  'princeton.edu': 'Princeton University',
  'columbia.edu': 'Columbia University',
  'upenn.edu': 'University of Pennsylvania',
  'brown.edu': 'Brown University',
  'dartmouth.edu': 'Dartmouth College',
  'cornell.edu': 'Cornell University',
  'stanford.edu': 'Stanford University',
  'mit.edu': 'Massachusetts Institute of Technology (MIT)',
  'caltech.edu': 'California Institute of Technology (Caltech)',
  'cmu.edu': 'Carnegie Mellon University',
  'duke.edu': 'Duke University',
  'northwestern.edu': 'Northwestern University',
  'nd.edu': 'University of Notre Dame',
  'vanderbilt.edu': 'Vanderbilt University',
  'emory.edu': 'Emory University',
  'rice.edu': 'Rice University',
  'wustl.edu': 'Washington University in St. Louis',
  'georgetown.edu': 'Georgetown University',
  'nyu.edu': 'New York University (NYU)',
  'bu.edu': 'Boston University',
  'northeastern.edu': 'Northeastern University',
  'usc.edu': 'University of Southern California (USC)',
  'buffalo.edu': 'University at Buffalo (SUNY)',
  'umich.edu': 'University of Michigan',
  'unc.edu': 'University of North Carolina at Chapel Hill',
  'uva.edu': 'University of Virginia',
  'gatech.edu': 'Georgia Institute of Technology',
  'utexas.edu': 'University of Texas at Austin',
  'ucla.edu': 'University of California, Los Angeles (UCLA)',
  'berkeley.edu': 'University of California, Berkeley',
  'ucsd.edu': 'University of California, San Diego',
  'ucdavis.edu': 'University of California, Davis',
  'uci.edu': 'University of California, Irvine',
  'ucsb.edu': 'University of California, Santa Barbara',
  'uw.edu': 'University of Washington',
  'wisc.edu': 'University of Wisconsin-Madison',
  'umn.edu': 'University of Minnesota',
  'osu.edu': 'Ohio State University',
  'psu.edu': 'Pennsylvania State University',
  'illinois.edu': 'University of Illinois Urbana-Champaign',
  'purdue.edu': 'Purdue University',
  'iu.edu': 'Indiana University Bloomington',
  'ufl.edu': 'University of Florida',
  'fsu.edu': 'Florida State University',
  'tamu.edu': 'Texas A&M University',
  'rutgers.edu': 'Rutgers University',
  'umd.edu': 'University of Maryland',
  'virginia.edu': 'University of Virginia',
  'umass.edu': 'University of Massachusetts Amherst',
};

/** Extract domain from email and return matching university, or empty string. */
export function universityFromEmail(email: string): string {
  const domain = email.split('@')[1]?.toLowerCase();
  return (domain && DOMAIN_TO_UNIVERSITY[domain]) || '';
}
